#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_hello="0.0.1"
  jq -n --arg hello "$ver_hello" '{hello: $hello}'
}

version "$@"
